/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.lang.ClassNotFoundException;

public class Main {

	public static void main(String[] args) throws SQLException {
		
		System.out.println("Hola mundo");
		Connection conexion = null;

		
		try {
			String url = "jdbc:mysql://localhost:6033/biblioteca";
			Class.forName("com.mysql.cj.jdbc.Driver");
			
			conexion = DriverManager.getConnection(url,"developer","programaciondaw");
			
			String sql = "SELECT * FROM libro;";
			
			Statement sentencia = conexion.createStatement();
			
			sentencia.executeUpdate("INSERT INTO libro VALUES ('libro5','123096789','NOVELA','autor4',200)");
			
			ResultSet rs = sentencia.executeQuery(sql);
			
			while(rs.next()) {
				System.out.println(rs.getString(1) + ", " + rs.getString(2) + ", " + rs.getString(3) + ", " + rs.getString(4) + ", " + rs.getString(5));
			}
			
		} catch (ClassNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (SQLException e1) {
			e1.printStackTrace();
		} finally {
			conexion.close();
		}

	}
}
